Revert change made in: http://svn.apache.org/viewvc/webservices/commons/trunk/modules/axiom/modules/axiom-dom/src/main/java/org/apache/axiom/om/impl/dom/ChildNode.java?r1=642096&r2=642095&pathrev=642096
Which is part of:
http://svn.apache.org/viewvc?view=rev&revision=642096

As it breaks Axis2/SAAJ:
------------------------------------------------------------------------------
Tests run: 24, Failures: 15, Errors: 9, Skipped: 0, Time elapsed: 0.072 sec <<< FAILURE!
testAddDetailsTwice(org.apache.axis2.saaj.SOAPFaultTest)  Time elapsed: 0.006 sec  <<< ERROR!
org.apache.axiom.om.OMException: Parent level elements cannot be detached
        at org.apache.axiom.om.impl.dom.ChildNode.detach(ChildNode.java:116)
        at org.apache.axiom.om.impl.dom.ElementImpl.discard(ElementImpl.java:1349)
        at org.apache.axiom.soap.impl.dom.SOAPFaultImpl.setNewElement(SOAPFaultImpl.java:148)
        at org.apache.axiom.soap.impl.dom.SOAPFaultImpl.setCode(SOAPFaultImpl.java:91)
        at org.apache.axiom.soap.impl.dom.soap11.SOAP11FaultImpl.setCode(SOAP11FaultImpl.java:73)
        at org.apache.axis2.saaj.SOAPFaultImpl.setFaultCode(SOAPFaultImpl.java:733)
        at org.apache.axis2.saaj.SOAPFaultImpl.setDefaults(SOAPFaultImpl.java:77)
        at org.apache.axis2.saaj.SOAPBodyImpl.addFault(SOAPBodyImpl.java:193)
        at org.apache.axis2.saaj.SOAPFaultTest.testAddDetailsTwice(SOAPFaultTest.java:169)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:45)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:599)
        at junit.framework.TestCase.runTest(TestCase.java:168)
        at junit.framework.TestCase.runBare(TestCase.java:134)
        at junit.framework.TestResult$1.protect(TestResult.java:110)
        at junit.framework.TestResult.runProtected(TestResult.java:128)
        at junit.framework.TestResult.run(TestResult.java:113)
        at junit.framework.TestCase.run(TestCase.java:124)
        at junit.framework.TestSuite.runTest(TestSuite.java:232)

git-svn-id: https://svn.apache.org/repos/asf/webservices/commons/trunk/modules/axiom@642246 13f79535-47bb-0310-9956-ffa450edef68